### PR TITLE
Display additional information for World & Avatar screens

### PR DESCRIPTION
**Pull request by CikeyQi**

### CODE REVIEW

**Comment by Nyabsi** [comment]
I had few little complaints, otherwise it looks good 👍🏻 

after you're addressed the highlighted issues please let me know by @me in this PR

**Comment by Nyabsi** [comment]
GridCells is supposed to be adaptive so it scales properly on Tablet screens, why was this change done?

**Comment by Nyabsi** [comment]
and PS. I suggest doing it like this:

two options:

- Adaptive
- Fixed

If Adaptive, it will automatically scale

if Fixed, UI will show slider which allows to set the amount of elements per row

**Comment by CikeyQi** [comment]
Sorry, it's my mistake. The reason I did this is that it appears large on my testing device. You're right, and I will make the necessary changes.

**Comment by Nyabsi** [comment]
If it shows too large on your testing device, we could look into adapting a different size for it that could scale better across screens that would be most ideal solution :) Also preferrably could you keep the changes in separate pull requests? For sake of clarity.

**Comment by Nyabsi** [comment]
Please take a look at these lines of code:

https://github.com/Nyabsi/VRCAA/blob/main/app/src/main/java/cc/sovellus/vrcaa/App.kt#L48-L52

https://github.com/Nyabsi/VRCAA/blob/main/app/src/main/java/cc/sovellus/vrcaa/extension/PreferencesExtension.kt#L91-L93

https://github.com/Nyabsi/VRCAA/blob/main/app/src/main/java/cc/sovellus/vrcaa/ui/screen/theme/ThemeScreen.kt#L93-L119

https://github.com/Nyabsi/VRCAA/blob/main/app/src/main/java/cc/sovellus/vrcaa/ui/screen/theme/ThemeScreenModel.kt#L13-L14

https://github.com/Nyabsi/VRCAA/blob/main/app/src/main/java/cc/sovellus/vrcaa/ui/components/misc/Logo.kt#L25

It shows how to implement settings properly.

**Comment by Nyabsi** [comment]
That looks okay, can you please split all the changes into their own branches and pull requests?

- Add setting for Column Count

This would contain changes related to the setting for the Column count.

- Display additional information for World, Avatar and Group screens (this)

This would contain changes related to world and avatar screen information extension

- Add Search for Feed

This would implement search for feed tab

**Pull request closed without merging**
