### PR TITLE
Add column count setting and feed search functionality.

### PR DESCRIPTION
**Pull request by CikeyQi**
* Add setting for Column Count

This would contain changes related to the setting for the Column count

* Display additional information for World, Avatar and Group screens

This would contain changes related to world and avatar screen information extension

* Add Search for Feed

This would implement search for feed tab

### CODE REVIEW

**Comment by CikeyQi** [comment]
My device is not working, so I can only put them together. I’m very sorry.

**Comment by Nyabsi** [comment]
This is starting to look good, I still have few nitpicks.

Please change the capitalization of "ID" to "Id" in strings, you can keep ID in Chinese if that's how it is, but you should set it to "Id" for rest of the languages, especially English as it is the source string.

You should remove the "platform" from WorldInfoScreen.kt as this is already present in the information, and I have plans for adjusting the way this information is presented.

For now, it can stay in AvatarScreen.kt as there is no way of presenting the data, but please remove the Unity package version considering this is information serves no practical purpose.

Instead of calling the default option of "column_count_options" "Auto" please rename it to "Adaptive" as it should automatically adjust, and I think having power of 2 increments so it can only be 2, 4 or 6 should be better in my opinion.

In code this can be implemented by making sure it's not 0 and then doing 2^i

instead of implementing search in feed with OutlinedTextField, consider implementing it similarly to the main page, you can take reference here: https://github.com/Nyabsi/VRCAA/blob/main/app/src/main/java/cc/sovellus/vrcaa/ui/screen/navigation/NavigationScreen.kt#L169-L268

**Comment by CikeyQi** [comment]
Thank you very much for correcting my mistakes. I will make sure to pay more attention to these issues in the future.
For this Pull Request, I have enabled the “Allow edits and access to secrets by maintainers” feature, so you can directly make changes to my errors on this page without needing me to open a new Pull Request. I really appreciate your assistance!

**Comment by Nyabsi** [comment]
I have made the required changes that I felt were necessary, please correct the values.xml files

Please change rest of the strings with the example I've outlined in strings.xml

**Comment by CikeyQi** [comment]
In the search functionality of the Feed, it seems to me that its main purpose should be keyword filtering. Perhaps it would enhance the user experience if filtering occurred whenever the content of the input field changes, and the input field is cleared when the back arrow is clicked?

**Comment by Nyabsi** [comment]
Indeed that's a great idea, that's what we'll do.

I think this PR is ready to merge, I will be doing a final review before that, and once that is complete I will be merging these changes.

**Comment by CikeyQi** [comment]
In AvatarScreen.kt, it may be necessary to use LazyColumn; otherwise, the information will not be displayed completely.

**Comment by Nyabsi** [comment]
usage of LazyColumn is actually not encouraged, that was a design mistake on my part during early days of the project.

instead we should apply `.verticalScroll(rememberScrollState())` to the Column.

Exception to this is when LazyColumn is used to display a list of elements, as it's intended.

**Comment by Nyabsi** [comment]
Merging, thanks for the contribution.

**Pull request merged**
